Collectif-Recolte/allotomat

- Sig.App.Frontend/src/components/admin/user-filters.vue
@sdthibault @ericforgues Je vous ajoute, mais c'est vraiment un micro changement.
> Display reset user list search when text is enter in Input

- Sig.App.Backend/Gql/Schema/GraphTypes/CardGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/IAddingFundTransactionGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/ManuallyAddingFundTransactionGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/OffPlatformAddingFundTransactionGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/SubscriptionAddingFundTransactionGraphType.cs
- Sig.App.Frontend/src/components/product-groups/product-group-fund-list.vue
- Sig.App.Frontend/src/views/card/Balance.vue
https://sigmund-ca.atlassian.net/browse/CRCL-1754
> Add expiration date on Balance check

- Sig.App.Backend/Helpers/SubscriptionHelper.cs
That could return a negatif value in case of an Expired subscription
https://sigmund-ca.atlassian.net/browse/CRCL-1728
> Fix issue with GetPaymentRemaining

- Sig.App.Backend/BackgroundJobs/SendMonthlyBalanceReport.cs
- Sig.App.Backend/Helpers/SubscriptionHelper.cs
Fix issue with groupBy in SendMonthlyBalance (Card instead of Organization since Organization is not always set in case of a GiftCard payment)
https://sigmund-ca.atlassian.net/browse/CRCL-1731
> Fix issue with groupBy in SendMonthlyBalance

- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
Add emptypage case for Organization without participant and Organization with participant without the subscriptionType
https://sigmund-ca.atlassian.net/browse/CRCL-1853
> Add emptypage case for Organization

- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
https://sigmund-ca.atlassian.net/browse/CRCL-1844
> Add tooltip to order by in Assign subscription

- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
https://sigmund-ca.atlassian.net/browse/CRCL-1845
> Add a disable state for order in assign page

- Sig.App.Backend/Gql/Schema/GraphTypes/BeneficiaryGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/BeneficiarySubscriptionTypeGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/OffPlatformBeneficiaryGraphType.cs
- Sig.App.Backend/Requests/Queries/DataLoaders/GetBeneficiarySubscription.cs
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-actions.vue
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-table.vue
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-with-detail.vue
- Sig.App.Frontend/src/components/card/card-assignation-list.vue
- Sig.App.Frontend/src/components/card/card-assignation-table.vue
- Sig.App.Frontend/src/views/beneficiary/EditAssociatedSubscriptions.vue
- Sig.App.Frontend/src/views/beneficiary/ListBeneficiaries.vue
- Sig.App.Frontend/src/views/beneficiary/ManuallyAddFund.vue
Adjust beneficiary-type check for conflict to fix issue when the subscription have beneficiary type but the beneficiary have changed is type since the assignation
https://sigmund-ca.atlassian.net/browse/CRCL-1750
> Adjust beneficiary-type check for conflict

- Sig.App.Frontend/src/components/product-groups/product-group-fund-list.vue
- Sig.App.Frontend/src/components/ui/generic/card-balance.vue
- Sig.App.Frontend/src/views/card/Balance.vue
Ça touche cette tâche https://sigmund-ca.atlassian.net/browse/CRCL-1830 et celle-ci https://sigmund-ca.atlassian.net/browse/CRCL-1814
> Fix intégration solde

- Sig.App.Backend/BackgroundJobs/ExpireFundsFromCard.cs
- Sig.App.BackendTests/BackgroundJobs/ExpireFundsFromCardTest.cs
When funds expired return the amount to budget allowance if the subscription is not yet expired.
https://sigmund-ca.atlassian.net/browse/CRCL-1891
> When funds expired return the amount to budget allowance

- Sig.App.Frontend/src/components/card/card-summary-table.vue
- Sig.App.Frontend/src/views/card/_index.vue
https://sigmund-ca.atlassian.net/browse/CRCL-1897
> Add funds available on cards in Card list

- Sig.App.Backend/Requests/Queries/Beneficiaries/SearchBeneficiaries.cs
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-filters.vue
- Sig.App.Frontend/src/components/ui/filter.vue
- Sig.App.Frontend/src/lib/consts/beneficiary-sort-order.js
- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
- Sig.App.Frontend/src/views/beneficiary/ListBeneficiaries.vue
https://sigmund-ca.atlassian.net/browse/CRCL-984
> Add sort order for beneficiary list

- Sig.App.Frontend/src/components/beneficiaries/beneficiary-actions.vue
- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
[[Roots / Trousses] Ajouter l'action «Attribuer abonnement» au menu pop-up d'un-e participant-e](https://sigmund-ca.atlassian.net/browse/CRCL-1755)
> Add possibility to assign a subscription to a specific participant

- Sig.App.Frontend/src/components/transaction/program-transaction-table.vue
- Sig.App.Frontend/src/views/transaction/ListTransactions.vue
[[FMNCP] Les noms des participant-es sont visibles dans le tableau de transactions pour un programme anonyme](https://sigmund-ca.atlassian.net/browse/CRCL-1801)
> Hide participant name if program have beneficiariesAreAnonymous

- Sig.App.Backend/Requests/Commands/Mutations/Beneficiaries/EditBeneficiary.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Beneficiaries/EditBeneficiaryTest.cs
- Sig.App.Frontend/src/views/beneficiary/EditBeneficiary.vue
Not already assign to a Beneficiary in the current Organization
[[Participant] Il est possible de donner le même identifiant unique 1 à 2 participants en éditant la fiche de ceux-ci dans l'app](https://sigmund-ca.atlassian.net/browse/CRCL-1346)
> Add a validation in Beneficiary edit for ID1 and ID2

- Sig.App.Backend/BackgroundJobs/AddingFundToCard.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/SubscriptionGraphType.cs
- Sig.App.Backend/Requests/Commands/Mutations/Subscriptions/AssignBeneficiariesToSubscription.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Subscriptions/AssignBeneficiariesToSubscriptionTest.cs
- Sig.App.Frontend/src/components/ui/dialog/warning-modal.vue
- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
[[Trousses / Roots] Répliquer un versement automatisé dans l'interface d'ajout manuel des fonds
](https://sigmund-ca.atlassian.net/browse/CRCL-1756)
Première portion seulement (ajout automatique lors de l'assignation). La suite arrive dans un autre PR.
> Add Replicate automated payment option when subscription is added 

- Sig.App.Frontend/src/views/beneficiary/ManuallyAddFund.vue
[Transfert manuel de fonds : Plusieurs erreurs sont affichées](https://sigmund-ca.atlassian.net/browse/CRCL-1941)
> Fix issue with card reference sometime null in AddManuallyFund view

- Sig.App.Backend/BackgroundJobs/AddingFundToCard.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/BeneficiarySubscriptionTypeGraphType.cs
- Sig.App.Backend/Gql/Schema/Mutation.cs
- Sig.App.Backend/Requests/Commands/Mutations/Subscriptions/AssignBeneficiariesToSubscription.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/AddMissingPayment.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Subscriptions/AssignBeneficiariesToSubscriptionTest.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Transactions/AddMissingPaymentTest.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Transactions/CreateManuallyAddingFundTransactionTest.cs
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-actions.vue
- Sig.App.Frontend/src/components/ui/dialog/warning-modal.vue
- Sig.App.Frontend/src/lib/consts/urls.js
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/beneficiary/AddMissedPayment.vue
- Sig.App.Frontend/src/views/beneficiary/ListBeneficiaries.vue
[[Trousses / Roots] Répliquer un versement automatisé dans l'interface d'ajout manuel des fonds](https://sigmund-ca.atlassian.net/browse/CRCL-1756)
> Add replicate manually missed payment to a card

- Sig.App.Frontend/src/components/app/main-menu.vue
- Sig.App.Frontend/src/components/dashboard/organization-dashboard.vue
- Sig.App.Frontend/src/components/dashboard/program-dashboard.vue
- Sig.App.Frontend/src/components/dashboard/subscription-stats-table.vue
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/dashboard/index.vue
[[Participants] En tant qu'Organisme, je veux consulter les détails des abonnements en cours, leurs montants restants, leurs dates d’expiration, etc.](https://sigmund-ca.atlassian.net/browse/CRCL-1476)
> Add Dashboard for Group (anciennement Organization)

- Sig.App.Frontend/src/components/ui/stepper.vue
- Sig.App.Frontend/src/views/subscription/_Form.vue
[[Abonnements] Ajustements à l'interface de création d'abonnement](https://sigmund-ca.atlassian.net/browse/CRCL-1951)
> Adjust subscription interface

- Sig.App.Backend/DataSeeders/DevDataSeeder.cs
- Sig.App.Backend/Gql/Schema/Query.cs
- Sig.App.Backend/Requests/Queries/Transactions/GenerateTransactionsReportForMarket.cs
- Sig.App.Backend/Services/Reports/IReportService.cs
- Sig.App.Backend/Services/Reports/ReportService.cs
- Sig.App.Frontend/src/views/transaction/MarketListTransaction.vue
[[Transactions] Permettre aux marchands d'exporter leurs transactions](https://sigmund-ca.atlassian.net/browse/CRCL-1368)
> Add export transaction report for merchant / Fix issue with SeedData CreatedDate

- Sig.App.Frontend/src/components/dashboard/program-dashboard.vue
- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
- Sig.App.Frontend/src/views/beneficiary/ListBeneficiaries.vue
- Sig.App.Frontend/src/views/card/_index.vue
[Permettre plusieurs sélection dans certains menus drop-down de filtres](https://sigmund-ca.atlassian.net/browse/CRCL-1995)
> Allow multiple selection to filter without hidden filter

- Sig.App.Frontend/pinkflamant/components/form/field/index.vue
- Sig.App.Frontend/pinkflamant/components/form/field/label.vue
- Sig.App.Frontend/pinkflamant/components/form/input/checkbox.vue
- Sig.App.Frontend/pinkflamant/components/form/input/radio-group.vue
- Sig.App.Frontend/pinkflamant/components/form/input/select.vue
- Sig.App.Frontend/pinkflamant/components/form/input/text.vue
- Sig.App.Frontend/pinkflamant/components/form/input/textarea.vue
- Sig.App.Frontend/src/views/beneficiary/_Form.vue
[[Participants] Indiquer les champs obligatoires dans l'interface de modification des infos d'un-e participant-e](https://sigmund-ca.atlassian.net/browse/CRCL-2031)
> Add mandatory field option in FormField / FormFieldLabel

- Sig.App.Backend/Gql/Schema/Mutation.cs
- Sig.App.Backend/Requests/Commands/Mutations/Subscriptions/AssignSubscriptionsToBeneficiary.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Subscriptions/AssignSubscriptionsToBeneficiaryTest.cs
- Sig.App.Frontend/src/components/beneficiaries/assign-subscription.vue
- Sig.App.Frontend/src/views/beneficiary/AddBeneficiary.vue
- Sig.App.Frontend/src/views/beneficiary/_AssignSubscriptionForm.vue
[[Ajout et traitement d'un-e participant-e à la fois] Étape d'assignation d'un abonnement](https://sigmund-ca.atlassian.net/browse/CRCL-2074)
> Add assign subscription to new participant creation flow

- Sig.App.Backend/Gql/DataLoader.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/BeneficiarySubscriptionTypeGraphType.cs
- Sig.App.Backend/Gql/Schema/Mutation.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/AddMissingPayment.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/AddMissingPayments.cs
- Sig.App.Backend/Requests/Queries/DataLoaders/GetSubscriptionTypeByBeneficiaryAndSubscriptionId.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Transactions/AddMissingPaymentsTest.cs
- Sig.App.Frontend/src/views/beneficiary/AddBeneficiary.vue
- Sig.App.Frontend/src/views/beneficiary/_AddMissedPayment.vue
[Ajout d'un versement manqué](https://sigmund-ca.atlassian.net/browse/CRCL-2076)
> Add the possibility to add missed payment at the end of the Create Beneficiary steppers

- Sig.App.Backend/Gql/DataLoader.cs
- Sig.App.Backend/Requests/Queries/Beneficiaries/ExportBeneficiariesList.cs
- Sig.App.Backend/Requests/Queries/Beneficiaries/ExportOffPlatformBeneficiariesList.cs
- Sig.App.Backend/Requests/Queries/DataLoaders/GetCardByCardNumbers.cs
- Sig.App.Backend/Services/Reports/ReportService.cs
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-with-detail.vue
- Sig.App.Frontend/src/components/card/card-summary-table.vue
- Sig.App.Frontend/src/views/card/EnableCard.vue
- Sig.App.Frontend/src/views/card/UnlockCard.vue
- Sig.App.Frontend/src/views/transaction/AddTransaction.vue
- Sig.App.Frontend/src/views/transaction/ManuallyEnterCardNumber.vue
[Uniformiser le format du numéro à 16 chiffres pour les cartes](https://sigmund-ca.atlassian.net/browse/CRCL-1347)
> Standardize card number to display XXXX XXXX XXXX XXXX

- Sig.App.Backend/Gql/Bases/TransactionsPagination.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/CardGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/ExpireFundTransactionGraphType.cs
- Sig.App.Backend/Requests/Queries/Transactions/SearchTransactions.cs
- Sig.App.Frontend/src/components/app/main-menu.vue
- Sig.App.Frontend/src/components/transaction/transaction-list.vue
- Sig.App.Frontend/src/views/beneficiary/_AssignSubscriptionForm.vue
- Sig.App.Frontend/src/views/card/Balance.vue
[[Solde] Afficher plus d'infos dans l'interface de consultation de solde d'un-e participant-e](https://sigmund-ca.atlassian.net/browse/CRCL-2028)
> Add transaction list in Balance Check / Add balance check for market

- Sig.App.Backend/Services/Cards/CardService.cs
- Sig.App.Frontend/src/components/ui/cta.vue
- Sig.App.Frontend/src/views/beneficiary/_AssignSubscriptionForm.vue
- Sig.App.Frontend/src/views/transaction/MarketManuallyEnterCardNumber.vue
- Sig.App.Frontend/src/views/transaction/NewScan.vue
- Sig.App.Frontend/src/views/transaction/Transaction.vue
[[Transaction] Commerce - Pouvoir faire une transaction en entrant le numéro de la carte manuellement](https://sigmund-ca.atlassian.net/browse/CRCL-391)
> Feature/crcl 391 market create transaction 16 digit card-number

- Sig.App.Backend/Gql/Schema/GraphTypes/ProjectGraphType.cs
- Sig.App.Backend/Gql/Schema/Query.cs
- Sig.App.Backend/Requests/Queries/Beneficiaries/ExportBeneficiariesList.cs
- Sig.App.Backend/Requests/Queries/Beneficiaries/SearchBeneficiaries.cs
- Sig.App.Frontend/src/components/beneficiaries/beneficiary-with-detail.vue
- Sig.App.Frontend/src/components/beneficiaries/list-beneficiaries-detailed.vue
- Sig.App.Frontend/src/views/beneficiary/ListBeneficiaries.vue
[[Prog] Améliorer l'exportation de tous les participant-es d'un programme](https://sigmund-ca.atlassian.net/browse/CRCL-1430)
> Add All group option in participant list / Add filter in participants export

- Sig.App.Backend/Gql/Bases/MarketAmountOwedPagination.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/MarketAmountOwedGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/ProjectGraphType.cs
- Sig.App.Backend/Requests/Queries/Markets/SearchMarketAmountOweds.cs
- Sig.App.Frontend/src/components/app/secondary-menu.vue
- Sig.App.Frontend/src/components/report/market-amount-owed-table.vue
- Sig.App.Frontend/src/components/report/report-filters.vue
- Sig.App.Frontend/src/lib/consts/urls.js
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/report/ReconciliationReport.vue
[[Rapport de réconciliation] Tableau des montants dûs aux commerces](https://sigmund-ca.atlassian.net/browse/CRCL-2041)
> Add reconciliation report for program

- Sig.App.Frontend/src/views/beneficiary/AddMissedPayment.vue
[[Ajout d'un abonnement] Permettre la fonctionnalité "Versement d'un paiement manqué" pour des abonnements non-accumulables #131](https://sigmund-ca.atlassian.net/browse/CRCL-2131)
> Fix issue with Subscription that don't have expiration date cant add missed funds

- Sig.App.Frontend/src/components/transaction/add-transaction.vue
- Sig.App.Frontend/src/views/transaction/AddTransaction.vue
- Sig.App.Frontend/src/views/transaction/SelectMarket.vue
[[Achat à partir d'un nom] Permettre d'afficher des infos additionelles](https://sigmund-ca.atlassian.net/browse/CRCL-2071)
> Display additional information to create a transaction from organization

- Sig.App.Backend/BackgroundJobs/AddingFundToCard.cs
- Sig.App.Backend/BackgroundJobs/RefreshCardBalance.cs
- Sig.App.Backend/Startup.cs
Add a migration to Refresh the balance according to the Transaction table (the hangfire task will never automaticly fire) / Change the AddSubscriptionTransaction to fire 4h after the Expiration
[Critique - Les transactions ne marchent pas pour un programme #135](https://sigmund-ca.atlassian.net/browse/CRCL-2150)
> Fix issue with outdated balance

- Sig.App.Backend/Gql/Schema/Mutation.cs
- Sig.App.Backend/Requests/Commands/Mutations/CashRegisters/AddCashRegisterToMarketGroup.cs
- Sig.App.Backend/Requests/Commands/Mutations/MarketGroups/AddMarketToMarketGroup.cs
- Sig.App.Backend/Requests/Commands/Mutations/Markets/CreateMarket.cs
- Sig.App.Backend/Requests/Commands/Mutations/Projects/AddMarketToProject.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/CashRegisters/AddCashRegisterToMarketGroupTest.cs
- Sig.App.Frontend/src/components/cash-register/cash-register-actions.vue
- Sig.App.Frontend/src/lib/consts/urls.js
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/cash-register/AddCashRegisterToMarketGroup.vue
- Sig.App.Frontend/src/views/cash-register/_Form.vue
- Sig.App.Frontend/src/views/market-groups/AddMarketToMarketGroup.vue
- Sig.App.Frontend/src/views/transaction/ListTransactions.vue
[[Caisse] Ajouter une caisse à un programme](https://sigmund-ca.atlassian.net/browse/CRCL-2169)
> Add the possibility to add a Program to a cash-register

- Sig.App.Backend/Helpers/SubscriptionHelper.cs
- Sig.App.Frontend/src/components/beneficiaries/assign-subscription.vue
- Sig.App.Frontend/src/views/beneficiary/AssignSubscriptions.vue
[Modifier l'info présentée dans cette modale](https://sigmund-ca.atlassian.net/browse/CRCL-2221)
> Fix issue with MaxNumberOfPayment not properly counted on the AssignSubscription screen when creating a beneficiary

- Sig.App.Frontend/src/components/beneficiaries/beneficiary-actions.vue
- Sig.App.Frontend/src/views/transaction/AddTransaction.vue
[Afficher pour les utilisateurs Prog le bouton «faire une transation» dans le menu pop-up des participant-es](https://sigmund-ca.atlassian.net/browse/CRCL-2210)
> Add Create transaction for program manager in Beneficiary list (like the group)

- Sig.App.Frontend/src/views/cash-register/AddCashRegister.vue
- Sig.App.Frontend/src/views/cash-register/_Form.vue
[NTH - Raccord - Revoir la modale d'ajout pour y afficher les bons type d'états](https://sigmund-ca.atlassian.net/browse/CRCL-2233)
> NTH state in Create register

- Sig.App.Frontend/src/views/cash-register/AddCashRegister.vue
- Sig.App.Frontend/src/views/cash-register/_Form.vue
Bugfix pour [[Caisse] Ajouter une caisse](https://sigmund-ca.atlassian.net/browse/CRCL-2062)
> Fix issue with marketgroup displayed in the MarketGroup list on CashRegister creation

- Sig.App.Frontend/src/views/subscription/_Form.vue
https://sigmund-ca.atlassian.net/browse/CRCL-2252
> Fix issue with monthly payment moment value used on subscription form submit

- Sig.App.Backend/Requests/Commands/Mutations/Transactions/CreateManuallyAddingFundTransaction.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/RefundTransaction.cs
- Sig.App.Frontend/src/lib/helpers/date.js
- Sig.App.Frontend/src/views/beneficiary/ManuallyAddFund.vue
- Sig.App.Frontend/src/views/subscription/EditSubscription.vue
[Rapport de transactions : filtrer par Abonnement ne fonctionne pas avec les remboursements #173](https://sigmund-ca.atlassian.net/browse/CRCL-2284)
> Fix issue with refund transaction not linked to Subscription

- Sig.App.Backend/Requests/Commands/Mutations/Transactions/CreateManuallyAddingFundTransaction.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/RefundTransaction.cs
- Sig.App.Backend/Requests/Queries/Organizations/GetOrganizationsStats.cs
- Sig.App.Backend/Services/Reports/ReportService.cs
- Sig.App.Frontend/src/lib/helpers/date.js
- Sig.App.Frontend/src/views/beneficiary/AddMissedPayment.vue
- Sig.App.Frontend/src/views/beneficiary/ManuallyAddFund.vue
- Sig.App.Frontend/src/views/subscription/EditSubscription.vue
[[Rapport] Valider le + ou - d'une transaction dans le rapport](https://sigmund-ca.atlassian.net/browse/CRCL-2166)
> Adjust report to return - for transaction of type RefundBudgetAllowance

- Sig.App.Backend/Controllers/AmazonSnsController.cs
- Sig.App.Backend/DbModel/AppDbContext.cs
- Sig.App.Backend/DbModel/Entities/BlacklistedEmail.cs
- Sig.App.Backend/Extensions/StringExtensions.cs
- Sig.App.Backend/Migrations/20250423134246_BlacklistedEmail.Designer.cs
- Sig.App.Backend/Migrations/20250423134246_BlacklistedEmail.cs
- Sig.App.Backend/Services/Mailer/BlacklistCheckingMailer.cs
- Sig.App.Backend/Services/Mailer/EmailBlacklistCache.cs
- Sig.App.Backend/Services/Mailer/EmailBlacklistService.cs
- Sig.App.Backend/Services/Mailer/IEmailBlacklistService.cs
- Sig.App.Backend/Startup.cs
- Sig.App.BackendTests/Mailer/BlacklistCheckingMailerTest.cs
[[Courriel] Passage vers AmazonSES](https://sigmund-ca.atlassian.net/browse/CRCL-2087)
Je suis partis du code de QI pour faire le bounce. De ce que j'ai vu des discussions avec Amazon, c'est la même demande que dans le temps avec QI. J'attends un retour officiel de la part d'Amazon à ce sujet.
> Add Amazon SES bounce support

- Sig.App.Backend/DbModel/Entities/Beneficiaries/Beneficiary.cs
- Sig.App.Backend/EmailTemplates/Models/TransactionBeneficiaryReceiptEmail.cs
- Sig.App.Backend/EmailTemplates/Models/TransactionRefundBeneficiaryReceiptEmail.cs
- Sig.App.Backend/EmailTemplates/TransactionBeneficiaryReceipt.cshtml
- Sig.App.Backend/EmailTemplates/TransactionRefundBeneficiaryReceipt.cshtml
- Sig.App.Backend/Gql/Schema/GraphTypes/BeneficiaryGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/IBeneficiaryGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/OffPlatformBeneficiaryGraphType.cs
- Sig.App.Backend/Gql/Schema/Mutation.cs
- Sig.App.Backend/Helpers/UrlHelper.cs
- Sig.App.Backend/Migrations/20250423203628_IsUnsubscribeToReceipt.Designer.cs
- Sig.App.Backend/Migrations/20250423203628_IsUnsubscribeToReceipt.cs
- Sig.App.Backend/Requests/Commands/Mutations/Beneficiaries/EditBeneficiary.cs
- Sig.App.Backend/Requests/Commands/Mutations/Beneficiaries/UnsubscribeBeneficiaryFromTransactionReceipt.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/CreateTransaction.cs
- Sig.App.Backend/Requests/Commands/Mutations/Transactions/RefundTransaction.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Beneficiaries/UnsubscribeBeneficiaryFromTransactionReceiptTest.cs
- Sig.App.Frontend/src/lib/consts/urls.js
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/beneficiary/EditBeneficiary.vue
- Sig.App.Frontend/src/views/beneficiary/UnsubscribeReceipt.vue
- Sig.App.Frontend/src/views/beneficiary/_Form.vue
[[Participants] Permettre de se désabonner des courriels de reçus d'achat](https://sigmund-ca.atlassian.net/browse/CRCL-2032)
> Add the possibility to unsubscribe from the transaction receipt as a Beneficiary

- Sig.App.Backend/Gql/Schema/Query.cs
- Sig.App.Backend/Requests/Queries/Transactions/GenerateTransactionsReport.cs
- Sig.App.Backend/Requests/Queries/Transactions/SearchTransactionLogs.cs
- Sig.App.Backend/Services/Reports/IReportService.cs
- Sig.App.Backend/Services/Reports/ReportService.cs
- Sig.App.Frontend/src/components/transaction/transaction-filters.vue
- Sig.App.Frontend/src/lib/consts/enums.js
- Sig.App.Frontend/src/views/transaction/ListTransactions.vue
- Sig.App.Frontend/src/views/transaction/MarketListTransaction.vue
[Ajouter un filtre au rapport de transactions : le "groupe" des cartes-cadeaux #148](https://sigmund-ca.atlassian.net/browse/CRCL-2204)
> Add gift card filters in transaction list

- Sig.App.Backend/Services/Reports/ReportService.cs
[Inclure un identifiant unique pour les marchés, groupes, et abonnements dans l'exportation des transactions #158](https://sigmund-ca.atlassian.net/browse/CRCL-2264)
> Add ID for Subscription / Market / Organization in Transaction report

- Sig.App.Frontend/src/components/transaction/add-transaction.vue
- Sig.App.Frontend/src/views/transaction/AddTransaction.vue
- Sig.App.Frontend/src/views/transaction/ManuallyEnterCardNumber.vue
- Sig.App.Frontend/src/views/transaction/SelectMarket.vue
[Associer une caisse avec une transaction Prog au nom d'un commerce #169](https://sigmund-ca.atlassian.net/browse/CRCL-2280)
> Add cash register on project created transaction

- Sig.App.Frontend/src/components/market/market-table.vue
- Sig.App.Frontend/src/views/market-groups/EditAssociatedMerchants.vue
- Sig.App.Frontend/src/views/market/ViewMarkets.vue
- Sig.App.Frontend/src/views/organization/EditAssociatedMerchants.vue
- Sig.App.Frontend/src/views/project/EditAssociatedMerchants.vue
[Tri erroné dans modal Commerces du Groupe de commerces](https://sigmund-ca.atlassian.net/browse/CRCL-2325)
> Fix issue market order in EditAssociatedMerchants (market-grouos, organization, project)

- Sig.App.Frontend/src/views/market-groups/EditAssociatedMerchants.vue
- Sig.App.Frontend/src/views/market/ListMarkets.vue
- Sig.App.Frontend/src/views/organization/EditAssociatedMerchants.vue
[Permettre d'enlever un commerce d'un Groupe de commerces #187](https://sigmund-ca.atlassian.net/browse/CRCL-2338)
> Fix issue with MarketTable delete button hiddenm

- Sig.App.Frontend/src/views/transaction/NewScan.vue
[[Marchand] La sélection des caisses ne prend pas pour acquis la possibilité que la caisse n'existe plus](https://sigmund-ca.atlassian.net/browse/CRCL-2343)
> Fix issue with auto-select cash-register when there's some cash-register archived

- Sig.App.Frontend/src/components/budget-allowance/budget-allowance-table.vue
- Sig.App.Frontend/src/lib/consts/urls.js
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/beneficiary/AvailableAmountForAllocation.vue
- Sig.App.Frontend/src/views/beneficiary/ListBeneficiaries.vue
[Permette de connaître facilement les sous-montants des enveloppes #175](https://sigmund-ca.atlassian.net/browse/CRCL-2328)
> Add budget allowance details modal in Assign Participants view

- Sig.App.Backend/BackgroundJobs/SendMonthlyCardBalanceReport.cs
- Sig.App.Backend/EmailTemplates/Models/MonthlyCardBalanceReportEmail.cs
- Sig.App.Backend/EmailTemplates/MonthlyCardBalanceReport.cshtml
- Sig.App.Backend/Gql/Schema/Query.cs
- Sig.App.Backend/Helpers/CardHelper.cs
- Sig.App.Backend/Requests/Queries/Beneficiaries/ExportBeneficiariesList.cs
- Sig.App.Backend/Requests/Queries/Cards/CardBalanceReport.cs
- Sig.App.Backend/Requests/Queries/Cards/ExportCardsList.cs
- Sig.App.Backend/Startup.cs
- Sig.App.Frontend/src/views/card/_index.vue
[Pouvoir connaître les soldes de toutes les cartes à un point donné #171](https://sigmund-ca.atlassian.net/browse/CRCL-2283)
> Add a report for Cards that include GiftCard

- Sig.App.Frontend/src/views/market-groups/EditManagers.vue
- Sig.App.Frontend/src/views/organization/EditManagers.vue
[Copier un lien d'invitation : « undefined » (au lieu de l'URL) #190](https://sigmund-ca.atlassian.net/browse/CRCL-2345)
> Fix issue with undefined confirmation link

- Sig.App.Backend/Requests/Commands/Mutations/Transactions/RefundTransaction.cs
- Sig.App.BackendTests/Requests/Commands/Mutations/Transactions/RefundTransactionTest.cs
- Sig.App.Frontend/pinkflamant/components/form/input/select.vue
- Sig.App.Frontend/src/views/transaction/ManuallyEnterCardNumber.vue
- Sig.App.Frontend/src/views/transaction/Refund.vue
- Sig.App.Frontend/src/views/transaction/SelectMarket.vue
[[Marchands] Bloquer les remboursements pour les marchands désactivés](https://sigmund-ca.atlassian.net/browse/CRCL-2341)
> Disabled refund and merchants is disabled

- Sig.App.Backend/BackgroundJobs/ExpireSubscription.cs
- Sig.App.Backend/BackgroundJobs/SendMonthlyBalanceReport.cs
- Sig.App.Backend/BackgroundJobs/SendMonthlyCardBalanceReport.cs
- Sig.App.Backend/DbModel/AppDbContext.cs
- Sig.App.Backend/DbModel/Entities/AppUser.cs
- Sig.App.Backend/DbModel/Entities/Profiles/EmailOptIn.cs
- Sig.App.Backend/Extensions/IdentityExtensions.cs
- Sig.App.Backend/Gql/DataLoader.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/UserEmailOptInGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/UserGraphType.cs
- Sig.App.Backend/Gql/Schema/Mutation.cs
- Sig.App.Backend/Migrations/20250814120728_EmailOptIn_AppUser.Designer.cs
- Sig.App.Backend/Migrations/20250814120728_EmailOptIn_AppUser.cs
- Sig.App.Backend/Requests/Commands/Mutations/Accounts/ChangeEmailOptIn.cs
- Sig.App.Backend/Requests/Commands/Mutations/Accounts/CreateAdminAccount.cs
- Sig.App.Backend/Requests/Commands/Mutations/Cards/CreateCards.cs
- Sig.App.Backend/Requests/Commands/Mutations/MarketGroups/AddManagerToMarketGroup.cs
- Sig.App.Backend/Requests/Commands/Mutations/MarketGroups/CreateMarketGroup.cs
- Sig.App.Backend/Requests/Commands/Mutations/Markets/AddManagerToMarket.cs
- Sig.App.Backend/Requests/Commands/Mutations/Markets/CreateMarket.cs
- Sig.App.Backend/Requests/Commands/Mutations/Organizations/AddManagerToOrganization.cs
- Sig.App.Backend/Requests/Commands/Mutations/Organizations/CreateOrganizationInProject.cs
- Sig.App.Backend/Requests/Commands/Mutations/Projects/AddManagerToProject.cs
- Sig.App.Backend/Requests/Commands/Mutations/Projects/CreateProject.cs
- Sig.App.Backend/Requests/Queries/DataLoaders/GetEmailOptInByUserIds.cs
- Sig.App.Backend/Requests/Queries/Projects/GetProjectProjectManagers.cs
- Sig.App.Frontend/src/components/settings/email-opt-in-form.vue
- Sig.App.Frontend/src/views/account/Settings.vue
[[Email] Rendre les rapports de réconciliation mensuels opt-in](https://sigmund-ca.atlassian.net/browse/CRCL-2029)
> Add opt-in / opt-out for email for project-manager

- Sig.App.Backend/Gql/Bases/SubscriptionEndReportPagination.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/OrganizationGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/ProjectGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/SubscriptionEndReportGraphType.cs
- Sig.App.Backend/Gql/Schema/GraphTypes/SubscriptionEndTransactionGraphType.cs
- Sig.App.Backend/Requests/Queries/Organizations/SearchOrganizationSubscriptionEndReport.cs
- Sig.App.Backend/Requests/Queries/Projects/SearchProjectSubscriptionEndReport.cs
- Sig.App.Frontend/src/components/app/secondary-menu.vue
- Sig.App.Frontend/src/components/report/report-filters.vue
- Sig.App.Frontend/src/components/report/subscription-end-report-table.vue
- Sig.App.Frontend/src/lib/consts/urls.js
- Sig.App.Frontend/src/lib/router/routes.js
- Sig.App.Frontend/src/views/report/SubscriptionEndReport.vue
[Rapport de fin d'abonnement #167](https://sigmund-ca.atlassian.net/browse/CRCL-2267)
Voir dans les commentaires la nouvelle description de Liam
> Add Subscription End Report views (for project and group managers)
